<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VoucherSeeder extends Seeder
{
    public function run(): void
    {
        $vouchers = [
            [
                'voucher_id' => 1,
                'campaign_id' => 1,
                'code' => 'CINEDOT20',
                'voucher_type' => 'order',
                'discount_type' => 'percentage',
                'discount_value' => 20.00,
                'min_order_value' => 100000.00,
                'max_discount_value' => 50000.00,
                'valid_from' => '2026-06-01 00:00:00',
                'valid_until' => '2026-12-31 23:59:59',
                'system_limit' => 1000,
                'limit_per_user' => 1,
                'used_count' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_id' => 2,
                'campaign_id' => 1,
                'code' => 'HE2026',
                'voucher_type' => 'order',
                'discount_type' => 'fixed_amount',
                'discount_value' => 50000.00,
                'min_order_value' => 150000.00,
                'max_discount_value' => null,
                'valid_from' => '2026-06-01 00:00:00',
                'valid_until' => '2026-08-31 23:59:59',
                'system_limit' => 500,
                'limit_per_user' => 1,
                'used_count' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_id' => 3,
                'campaign_id' => 2,
                'code' => 'WELCOME50',
                'voucher_type' => 'order',
                'discount_type' => 'percentage',
                'discount_value' => 50.00,
                'min_order_value' => 50000.00,
                'max_discount_value' => 30000.00,
                'valid_from' => '2026-01-01 00:00:00',
                'valid_until' => '2026-12-31 23:59:59',
                'system_limit' => 2000,
                'limit_per_user' => 1,
                'used_count' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_id' => 4,
                'campaign_id' => 3,
                'code' => 'VIPMEMBER',
                'voucher_type' => 'order',
                'discount_type' => 'percentage',
                'discount_value' => 15.00,
                'min_order_value' => 200000.00,
                'max_discount_value' => 100000.00,
                'valid_from' => '2026-01-01 00:00:00',
                'valid_until' => '2026-12-31 23:59:59',
                'system_limit' => 1000,
                'limit_per_user' => 2,
                'used_count' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_id' => 5,
                'campaign_id' => 1,
                'code' => 'COMBO30',
                'voucher_type' => 'combo',
                'discount_type' => 'fixed_amount',
                'discount_value' => 30000.00,
                'min_order_value' => 80000.00,
                'max_discount_value' => null,
                'valid_from' => '2026-06-01 00:00:00',
                'valid_until' => '2026-12-31 23:59:59',
                'system_limit' => 800,
                'limit_per_user' => 1,
                'used_count' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_id' => 6,
                'campaign_id' => 4,
                'code' => 'NIGHTOWL',
                'voucher_type' => 'order',
                'discount_type' => 'percentage',
                'discount_value' => 25.00,
                'min_order_value' => 90000.00,
                'max_discount_value' => 40000.00,
                'valid_from' => '2026-05-01 00:00:00',
                'valid_until' => '2026-11-30 23:59:59',
                'system_limit' => 600,
                'limit_per_user' => 1,
                'used_count' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('vouchers')->insertOrIgnore($vouchers);
    }
}
